In [2]:
import numpy as np 

In [3]:
a=np.array([1,2,3],dtype=np.int32)

In [4]:
a.ndim

1

In [5]:
a[2]

3

In [6]:
b=np.array([[1,2,3],[2,1,3],[2,1,3]])

In [7]:
print(b.ndim)
b

2


array([[1, 2, 3],
       [2, 1, 3],
       [2, 1, 3]])

In [8]:
c=np.array([[[1,2],[2,3],[2,3]]])


In [9]:
print(c.ndim)
c

3


array([[[1, 2],
        [2, 3],
        [2, 3]]])

In [10]:
a.itemsize

4

In [11]:
x = np.array([1,2,3], dtype=np.float64)

In [12]:
x.itemsize
x


array([ 1.,  2.,  3.])

In [13]:
a.dtype

dtype('int32')

In [14]:
b.size

9

In [15]:
b

array([[1, 2, 3],
       [2, 1, 3],
       [2, 1, 3]])

In [16]:
b.shape

(3, 3)

In [17]:
c.shape


(1, 3, 2)

In [18]:
a

array([1, 2, 3], dtype=int32)

In [19]:
a.shape

(3,)

In [20]:
a.ndim

1

In [21]:
c=np.array([[1,2],[2,3],[2,3]])

In [22]:
c.ndim

2

In [23]:
c.size

6

In [24]:
c.shape

(3, 2)

In [25]:
c

array([[1, 2],
       [2, 3],
       [2, 3]])

In [26]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [27]:
np.zeros(3,)

array([ 0.,  0.,  0.])

In [28]:
a.shape

(3,)

In [29]:
c.shape

(3, 2)

In [30]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [31]:
np.ones(((4,2,2)))

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]]])

In [32]:
a=np.arange(1,5,2)

In [33]:
a

array([1, 3])

In [35]:
b=np.arange(1,5)
b


array([1, 2, 3, 4])

In [45]:
np.linspace(1,5,5)


array([ 1.,  2.,  3.,  4.,  5.])

In [46]:
   np.linspace(1,5,20) 

array([ 1.        ,  1.21052632,  1.42105263,  1.63157895,  1.84210526,
        2.05263158,  2.26315789,  2.47368421,  2.68421053,  2.89473684,
        3.10526316,  3.31578947,  3.52631579,  3.73684211,  3.94736842,
        4.15789474,  4.36842105,  4.57894737,  4.78947368,  5.        ])

In [52]:
array2=np.array([[1,2],[2,3],[3,4]])

In [53]:
array2

array([[1, 2],
       [2, 3],
       [3, 4]])

In [54]:
array2.shape

(3, 2)

In [55]:
array2.reshape(2,3)

array([[1, 2, 2],
       [3, 3, 4]])

In [67]:
print(array2.reshape(6,1))
array2

[[1]
 [2]
 [2]
 [3]
 [3]
 [4]]


array([[1, 2],
       [2, 3],
       [3, 4]])

In [64]:
array2.ravel()

array([1, 2, 2, 3, 3, 4])

In [65]:
array2

array([[1, 2],
       [2, 3],
       [3, 4]])

In [68]:
array2.min()

1

In [69]:
array2.max()

4

In [70]:
array2.sum()

15

In [72]:
array2.sum(axis=0)

array([6, 9])

In [73]:
array2.sum(axis=1)

array([3, 5, 7])

In [74]:
np.sqrt(array2)

array([[ 1.        ,  1.41421356],
       [ 1.41421356,  1.73205081],
       [ 1.73205081,  2.        ]])

In [75]:
np.std(array2)

0.9574271077563381