In [1]:
import numpy as np 

In [4]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])

In [5]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [6]:
a[1,2]

5

In [9]:
a[0:2,2]

array([3, 5])

In [10]:
a[-1]

array([5, 6, 7])

In [15]:
a[-1,2]

7

In [16]:
a[-1,0:2]

array([5, 6])

In [17]:
b=np.array([1,2,3])

In [18]:
b[0:2]

array([1, 2])

In [19]:
b[-1]

3

In [20]:
b

array([1, 2, 3])

In [21]:
b[:2]

array([1, 2])

In [22]:
b[2:]

array([3])

In [23]:
b[1:]

array([2, 3])

In [30]:
a[:,1:3]

array([[2, 3],
       [4, 5],
       [6, 7]])