# why numpy over list? 

Numpy Array: Less Memory, Fast and Convenient.

In [41]:
import numpy as np
import sys

In [42]:
a=np.array([1,2,3,2,5])

In [43]:
a[0]


1

In [44]:
a[3]

2

In [112]:
list1=range(1000)
print("size of list1:",sys.getsizeof(5)*len(list1))
print("length:",len(list1))

size of list1: 28000
length: 1000


In [113]:
array1= np.arange(1000)
print(array1.size* array1.itemsize)

8000


In [114]:
size=100

In [115]:
l1=range(size)
l2=range(size)

In [116]:
a1=np.arange(size)
a2=np.arange(size)

In [117]:
a=l1[1]
a


1

In [118]:
l1

range(0, 100)

In [119]:
import time
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("python list took:",(time.time()-start)*1000)
print(result)
print(start)

python list took: 0.7145404815673828
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]
1522417338.231951


In [120]:
start=time.time()
result =a1+a2
print("numpy array took:", (time.time()-start)*1000)
print(result)

numpy array took: 0.11348724365234375
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]


In [121]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])

In [122]:
a1+a2

array([ 6,  8, 10, 12])

In [123]:
a1-a2

array([-4, -4, -4, -4])

In [124]:
a1*a2

array([ 5, 12, 21, 32])

In [125]:
a1/a2

array([ 0.2       ,  0.33333333,  0.42857143,  0.5       ])

In [126]:
for a in range(-20,-10,1):
    print(a)

-20
-19
-18
-17
-16
-15
-14
-13
-12
-11
